apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: teamdeployagent-birdeye-api-key
  namespace: storefront-devteam
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: deepagent-aws
    kind: ClusterSecretStore
  target:
    name: app-env
    creationPolicy: Merge
  data:
    - secretKey: BIRDEYE_API_KEY
      remoteRef:
        key: storefront-dev/storefront-devteam/BIRDEYE_API_KEY
