apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: teamdeployagent-aws-secret-access-key
  namespace: storefront-devteam
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: deepagent-aws
    kind: ClusterSecretStore
  target:
    name: app-env
    creationPolicy: Merge
  data:
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: storefront-dev/storefront-devteam/AWS_SECRET_ACCESS_KEY
